[project]
name = "android-log-browser"
version = "0.1.0"
description = "CLI to parse and browse Android bugreport/dumpstate logs."
readme = "android_log_browser/README.md"
requires-python = ">=3.10"
dependencies = [
  "typer",
]

[project.scripts]
android-log-browser = "android_log_browser.main:app"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
